# Generated by Django 4.2.6 on 2023-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('url', models.URLField()),
                ('unique_id', models.SlugField(blank=True, max_length=6, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('shortened_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='URLShortener',
        ),
    ]
